### ISSUE TITLE
Purchase signup link is locked behind permissions

### ISSUE THREAD

**Issue by FishPhd** [tjhorner/upsy-desky#1]
Love the product! Looking to sign up to hear when they go on sale but the Google form has some permissions locking me out!

Link in question on the Readme: https://forms.gle/285GffmpfHamryEu6

Tha m you for making this! Excited to get my hands on it or build my own.

**Comment by tjhorner** [comment]
Ugh, that gets me every time. Just fixed it! Thanks for your interest :)
