### ISSUE TITLE
Consider adding fast_connect to WiFi options

### ISSUE THREAD

**Issue by TheRealAvise** [tjhorner/upsy-desky#16]
Maybe consider adding fast_connect option under WiFi, otherwise it can't connect to hidden SSID's.

**Comment by tjhorner** [comment]
I have actually tried this out before; ESPHome requires that a WiFi network is specified in the config for this option to be available. I'm unsure if they have changed this in recent versions, but I'll see if this is now possible. If it isn't, I'll raise an issue on ESPHome's side and maybe submit a PR to enable this functionality without specifying a network in the config

**Comment by TheRealAvise** [comment]
Ups, did not know that.

Maybe then just add to the wiki, as something to try, if WiFi SSID is hidden.

**Comment by tjhorner** [comment]
Yep, good idea! I'll add that to the troubleshooting doc

**Comment by tjhorner** [comment]
Added to the Getting Started docs
