### ISSUE TITLE
Ramping Down (soft stop)

### ISSUE THREAD

**Issue by zeel01** [tjhorner/upsy-desky#17]
I've noticed that when I command the desk to a specific height, it tends to sometimes miss the mark by around a quarter to half an inch. I also noticed that it tends to stop very abruptly. 

But when I use one of the 4 presets the movement actually ramps down when the desk get near the target height. It hits the target much more reliably this way, and with less of a jarring stop.

I'm wondering if this ramping could be achieved with go to commands as well. I worry somewhat that the hard stopping could cause excess wear, in addition to the annoyance of not actually hitting the target reliably.

**Comment by tjhorner** [comment]
So when you set the height with the "Target Desk Height" input, it actually emulates pressing the up or down button until it reaches close to the target height, so it's not exact.

When you press the preset buttons in the UI, it emulates pressing the physical preset buttons, and the desk's control box is smart enough to slow down when it approaches the preset height. Unfortunately, I can't replicate this behavior for arbitrary heights — the desk doesn't accept commands like "go to height XYZ".

I recommend using presets if you can, and only using the target desk height slider if you run out of presets.
