### ISSUE TITLE
Add a named default value for the height units

### ISSUE THREAD

**Issue by TheRealAvise** [tjhorner/upsy-desky#25]
As always thank you for the great device and continued work on the software part of it.

Would it be possible to add a named default value for the height units in the config.yaml, as it is done for the desk variant or the min/max height? Right now it is hard-coded to default to in.

This would allow for an easy substitution in ESPHome with whatever is considered the real default, in my case cm.

**Comment by tjhorner** [comment]
Sure, that shouldn't be too difficult. I'll add it in the next release

**Comment by tjhorner** [comment]
This has been added in the config in 16792d6954c4696b829f5c3187f07058d89bb184 (version 0.3.0)
