### ISSUE TITLE
Show current firmware version for OTA update

### ISSUE THREAD

**Issue by tomtastic** [tjhorner/upsy-desky#33]
Would it be possible to add details of the current firmware version to the web interface ?
![image](https://github.com/tjhorner/upsy-desky/assets/302127/6759edf2-78c6-4c0f-93c0-4691958544b8)

**Comment by tomtastic** [comment]
Very nice, thank you!

**Comment by tomtastic** [comment]
Just updated OTA, tried restarting, etc, but nothing new showing...

**Comment by tjhorner** [comment]
Oh, sorry about that — made a silly mistake and forgot something. I'll re-release as 1.1.1 shortly.

**Comment by tomtastic** [comment]
`v1.1.1` Works perfectly, thank you for the fast implementation!
